import { readFileSync, readdirSync, writeFileSync } from "node:fs";
const directory = new URL("../migrations/", import.meta.url);
const migrations = readdirSync(directory)
  .filter((name) => /^\d+.*\.sql$/.test(name))
  .sort()
  .map((name) => {
    // Top-level statements start in column 1. Trigger bodies are indented.
    const sql = readFileSync(new URL(name, directory), "utf8")
      .replace(/^--.*$/gm, "")
      .trim();
    const statements = sql
      .split(/\n(?=(?:CREATE|INSERT|ALTER|DROP|UPDATE|DELETE)\b)/)
      .map((statement) => statement.trim());
    // Migration 1 may already have been installed by an older Wrangler deployment.
    if (name.startsWith("0001_")) {
      for (let i = 0; i < statements.length; i++) {
        statements[i] = statements[i]
          .replace(/^CREATE (TABLE|INDEX|TRIGGER) /, "CREATE $1 IF NOT EXISTS ")
          .replace(/^INSERT INTO job/, "INSERT OR IGNORE INTO job");
      }
    }
    return { name, statements };
  });
writeFileSync(
  new URL("../src/schema-migrations.ts", import.meta.url),
  `// Generated by cloudflare/scripts/schema.mjs from the SQL migrations.\nexport const migrations = ${JSON.stringify(migrations, null, 2)} as const;\n`,
);
