// Generated by cloudflare/scripts/schema.mjs from the SQL migrations.
export const migrations = [
  {
    "name": "0001_analytics.sql",
    "statements": [
      "CREATE TABLE IF NOT EXISTS job (\n id INTEGER PRIMARY KEY CHECK(id=1), status TEXT NOT NULL DEFAULT 'idle', phase TEXT NOT NULL DEFAULT 'transactions',\n run_id TEXT NOT NULL DEFAULT '', since TEXT NOT NULL DEFAULT '', until_at TEXT NOT NULL DEFAULT '', window_start TEXT NOT NULL DEFAULT '', window_end TEXT NOT NULL DEFAULT '',\n cursor TEXT, windows_done INTEGER NOT NULL DEFAULT 0, windows_total INTEGER NOT NULL DEFAULT 0,\n pages INTEGER NOT NULL DEFAULT 0, records INTEGER NOT NULL DEFAULT 0, units_done INTEGER NOT NULL DEFAULT 0, units_total INTEGER NOT NULL DEFAULT 0,\n phase_cursor TEXT NOT NULL DEFAULT '', started_at TEXT, updated_at TEXT, phase_started_at TEXT, last_success TEXT,\n lease TEXT, lease_until INTEGER NOT NULL DEFAULT 0, paused INTEGER NOT NULL DEFAULT 0,\n failures INTEGER NOT NULL DEFAULT 0, retry_at INTEGER NOT NULL DEFAULT 0, error TEXT,\n window_started_at TEXT, samples TEXT NOT NULL DEFAULT '[]', price_signature TEXT NOT NULL DEFAULT '', version INTEGER NOT NULL DEFAULT 0\n);",
      "INSERT OR IGNORE INTO job(id) VALUES(1);",
      "CREATE TABLE IF NOT EXISTS transactions (\n id TEXT PRIMARY KEY, type TEXT NOT NULL, app_id TEXT NOT NULL, shop_id TEXT NOT NULL, charge_ref TEXT NOT NULL,\n created_at TEXT NOT NULL, billing_interval TEXT, gross_amount REAL NOT NULL, net_amount REAL NOT NULL,\n currency TEXT NOT NULL\n) WITHOUT ROWID;",
      "CREATE INDEX IF NOT EXISTS tx_shop ON transactions(shop_id,charge_ref,type,created_at);",
      "CREATE INDEX IF NOT EXISTS tx_charge ON transactions(charge_ref,type,billing_interval);",
      "CREATE INDEX IF NOT EXISTS tx_time ON transactions(created_at);",
      "CREATE TABLE IF NOT EXISTS app_events (\n event_key TEXT PRIMARY KEY, app_id TEXT NOT NULL, shop_id TEXT NOT NULL, type TEXT NOT NULL, occurred_at TEXT NOT NULL,\n charge_id TEXT NOT NULL, charge_name TEXT, charge_amount REAL, charge_currency TEXT, charge_test INTEGER NOT NULL, billing_on TEXT\n) WITHOUT ROWID;",
      "CREATE INDEX IF NOT EXISTS events_shop ON app_events(shop_id,charge_id,occurred_at);",
      "CREATE INDEX IF NOT EXISTS events_time ON app_events(occurred_at);",
      "CREATE TABLE IF NOT EXISTS shops(shop_id TEXT PRIMARY KEY) WITHOUT ROWID;",
      "CREATE TABLE IF NOT EXISTS dirty_shops(shop_id TEXT PRIMARY KEY) WITHOUT ROWID;",
      "CREATE TABLE IF NOT EXISTS due_shops(shop_id TEXT PRIMARY KEY, due_at TEXT NOT NULL) WITHOUT ROWID;",
      "CREATE INDEX IF NOT EXISTS due_time ON due_shops(due_at);",
      "CREATE TABLE IF NOT EXISTS price_hints(charge_id TEXT PRIMARY KEY, shop_id TEXT NOT NULL, plan_name TEXT NOT NULL, amount REAL NOT NULL, currency TEXT NOT NULL, interval TEXT NOT NULL) WITHOUT ROWID;",
      "CREATE INDEX IF NOT EXISTS price_shop ON price_hints(shop_id);",
      "CREATE INDEX IF NOT EXISTS price_group ON price_hints(plan_name,amount,currency,interval);",
      "CREATE TABLE IF NOT EXISTS shop_deltas(shop_id TEXT NOT NULL, date TEXT NOT NULL, currency TEXT NOT NULL, mrr_delta REAL NOT NULL, paying_delta INTEGER NOT NULL,\n PRIMARY KEY(shop_id,date,currency)) WITHOUT ROWID;",
      "CREATE TABLE IF NOT EXISTS daily(date TEXT NOT NULL, currency TEXT NOT NULL, mrr_delta REAL NOT NULL DEFAULT 0, paying_delta INTEGER NOT NULL DEFAULT 0,\n installs INTEGER NOT NULL DEFAULT 0, uninstalls INTEGER NOT NULL DEFAULT 0, reactivations INTEGER NOT NULL DEFAULT 0, deactivations INTEGER NOT NULL DEFAULT 0,\n gross REAL NOT NULL DEFAULT 0, net REAL NOT NULL DEFAULT 0, PRIMARY KEY(date,currency)) WITHOUT ROWID;",
      "CREATE TRIGGER IF NOT EXISTS tx_insert AFTER INSERT ON transactions BEGIN\n INSERT INTO daily(date,currency,gross,net) VALUES(substr(NEW.created_at,1,10),NEW.currency,NEW.gross_amount,NEW.net_amount)\n ON CONFLICT(date,currency) DO UPDATE SET gross=gross+excluded.gross,net=net+excluded.net;\nEND;",
      "CREATE TRIGGER IF NOT EXISTS tx_update AFTER UPDATE ON transactions BEGIN\n UPDATE daily SET gross=gross-OLD.gross_amount,net=net-OLD.net_amount WHERE date=substr(OLD.created_at,1,10) AND currency=OLD.currency;\n INSERT INTO daily(date,currency,gross,net) VALUES(substr(NEW.created_at,1,10),NEW.currency,NEW.gross_amount,NEW.net_amount)\n ON CONFLICT(date,currency) DO UPDATE SET gross=gross+excluded.gross,net=net+excluded.net;\nEND;",
      "CREATE TRIGGER IF NOT EXISTS event_insert AFTER INSERT ON app_events WHEN NEW.charge_test=0 BEGIN\n INSERT INTO daily(date,currency,installs,uninstalls,reactivations,deactivations)\n VALUES(substr(NEW.occurred_at,1,10),'',NEW.type='RELATIONSHIP_INSTALLED',NEW.type='RELATIONSHIP_UNINSTALLED',NEW.type='RELATIONSHIP_REACTIVATED',NEW.type='RELATIONSHIP_DEACTIVATED')\n ON CONFLICT(date,currency) DO UPDATE SET installs=installs+excluded.installs,uninstalls=uninstalls+excluded.uninstalls,reactivations=reactivations+excluded.reactivations,deactivations=deactivations+excluded.deactivations;\nEND;",
      "CREATE TRIGGER IF NOT EXISTS delta_insert AFTER INSERT ON shop_deltas BEGIN\n INSERT INTO daily(date,currency,mrr_delta,paying_delta) VALUES(NEW.date,NEW.currency,NEW.mrr_delta,NEW.paying_delta)\n ON CONFLICT(date,currency) DO UPDATE SET mrr_delta=mrr_delta+excluded.mrr_delta,paying_delta=paying_delta+excluded.paying_delta;\nEND;",
      "CREATE TRIGGER IF NOT EXISTS delta_delete AFTER DELETE ON shop_deltas BEGIN\n UPDATE daily SET mrr_delta=mrr_delta-OLD.mrr_delta,paying_delta=paying_delta-OLD.paying_delta WHERE date=OLD.date AND currency=OLD.currency;\nEND;",
      "CREATE TABLE IF NOT EXISTS auth_limits(key TEXT PRIMARY KEY, attempts INTEGER NOT NULL, expires INTEGER NOT NULL) WITHOUT ROWID;",
      "CREATE TABLE IF NOT EXISTS ai_cache(key TEXT PRIMARY KEY, text TEXT NOT NULL, created_at INTEGER NOT NULL) WITHOUT ROWID;"
    ]
  },
  {
    "name": "0002_session_key.sql",
    "statements": [
      "CREATE TABLE IF NOT EXISTS auth_settings(key TEXT PRIMARY KEY, value TEXT NOT NULL) WITHOUT ROWID;"
    ]
  }
] as const;
